global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  # Exposes port for data to be queried by grafana, can be viewed at localhost:9090/metrics, or queried at localhost:9090/graph
  - job_name: localprometheus
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090', 'node-exporter:9100', 'cadvisor:8080']

  # - job_name: 'federate'
  #   metrics_path: '/federate'
  #   scrape_interval: 15s
  #   honor_labels: true
  #   params:
  #     'match[]':
  #       - '{job="kubernetes-apiservers"}'
  #       - '{job="kubernetes-nodes"}'
  #       - '{job="kubernetes-nodes-cadvisor"}'
  #       - '{job="kubernetes-service-endpoints"}'
  #   static_configs:
  #     - targets:
  #       - 'host.docker.internal:45555'
  #       # - 'localhost:45555'
  #   relabel_configs:
  #     - target_label: 'federation'
  #       replacement: 'true'
  #     - target_label: 'scrapetype'
  #       replacement: 'kubernetes'