
FROM --platform=$BUILDPLATFORM node:18.12-alpine3.16

# copy sql init file to directory for postgres initialization
COPY imageConfigs/postgres postgres

# Creates and copies files to folders that docker-compose will use create named volumes from
COPY imageConfigs/prometheus prometheus
COPY imageConfigs/grafana grafana

# Starts the application
CMD ["tail", "-f", "/dev/null"]