# version: '3.9'

services:
  # The UI/Backend
  morpheus:
    build:
      context: ..
      dockerfile: morpheus/dockerfile.dev
    container_name: morpheus
    environment:
      - MODE=browser
      - STATUS=development
    volumes:
      # Opens the docker sock and creates named volumes for persistent data that can be shared between containers
      # - /var/run/docker.sock:/var/run/docker.sock
      - morpheus-prometheus-files:/prometheus
      - morpheus-grafana-files:/grafana
    # ports:
    #   - 3001:3001

  cadvisor:
    # Must use cadvisor v0.47.1 instead of latest, latest does not work for macOS
    # The morpheus image uploaded is on gcr.io/cadvisor/cadvisor:v0.47.1
    image: gcr.io/cadvisor/cadvisor:v0.47.1
    container_name: morpheus-cadvisor
    expose:
      - 8080
    ports:
      - 50000:8080
    volumes:
      # Applies the bind mounts in ro (read only) and rw (read write) to be able to scrape containers
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /etc/machine-id:/etc/machine-id:ro

  # Collects additional metrics that are then sent to prometheus
  node-exporter:
    image: prom/node-exporter:latest
    container_name: morpheus-node-exporter
    restart: unless-stopped
    expose:
      - 9100
    ports:
      - 50001:9100
    volumes:
      #system info for linux machines
      - /proc:/host/proc:ro
      # also for linux
      - /sys:/host/sys:ro
      #root
      - /:/rootfs:ro
    # Set up the node-exporter to scrape resource metrics
    # Dockerfile handles this if you're using the uploaded images
    command:
      - --path.procfs=/host/proc
      - --path.rootfs=/rootfs
      - --path.sysfs=/host/sys
      - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)
      - --log.level=error


  # Collects metrics and makes them available at localhost:9090
  prometheus:
    image: prom/prometheus:latest
    container_name: morpheus-prometheus
    restart: unless-stopped
    expose:
      - 9090
    ports:
      - 50002:9090
    volumes:
      - morpheus-prometheus-files:/etc/prometheus
      - morpheus-prometheus-data:/prometheus
    # Tells prometheus to use the config file from ./imageConfigs/prometheus
    # Dockerfile handles this if you're using the uploaded images
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --log.level=error
    depends_on:
      - node-exporter
      - cadvisor
      - morpheus

  # Displays metrics gathered from containers
  grafana:
    image: grafana/grafana:latest
    container_name: morpheus-grafana
    expose:
      - 3000
    ports:
      - 50003:3000
    volumes:
      - morpheus-grafana-files:/etc/grafana
    environment:
      GF_PATHS_CONFIG: /etc/grafana/grafana.ini
    depends_on:
      - prometheus

volumes:
  morpheus-prometheus-data:
  morpheus-prometheus-files:
  morpheus-grafana-files:
