
FROM --platform=$BUILDPLATFORM node:18.12-alpine3.16

# # Installs curl
# RUN apk --no-cache add curl

# # Update the DOCKERVERSION to the most recent version, check dates on https://download.docker.com/linux/static/stable/x86_64/
# # Installs docker to the image so it can run exec commands on the backend
# ENV DOCKERVERSION=24.0.5
# RUN curl -fsSLO https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKERVERSION}.tgz \
#   && tar xzvf docker-${DOCKERVERSION}.tgz --strip 1 -C /usr/local/bin docker/docker \
#   && rm docker-${DOCKERVERSION}.tgz

# # Copies over the dev compose file and renames it so when installing as extension it is recognized
# COPY extension/docker-compose-dev.yaml docker-compose.yaml

# Creates and copies files to folders that docker-compose will use create named volumes from
COPY imageConfigs/prometheus prometheus
COPY imageConfigs/grafana grafana

# Starts the application
CMD ["tail", "-f", "/dev/null"]